- name: Add Asterisk user
  remote_user: root
  shell: adduser --system --group --home /var/lib/asterisk --no-create-home --gecos "Asterisk PBX" asterisk
  args:
    executable: /bin/bash
  tags:
    - asterisk
    - system
- name: Add Asterisk user to "dialout" and "audio" groups
  remote_user: root
  shell: usermod -a -G dialout,audio asterisk
  args:
    executable: /bin/bash
  tags:
    - asterisk
    - system
- name: Configure Asterisk to run as user "asterisk"
  remote_user: root
  blockinfile:
    path: /etc/default/asterisk
    block: |
      AST_USER="asterisk"
      AST_GROUP="asterisk"
    backup: yes
  tags:
    - asterisk
    - system
- name: Change owner of Asterisk-related files and directories
  remote_user: root
  shell: "chown -R asterisk: /var/{lib,log,run,spool}/asterisk /usr/lib/asterisk /etc/asterisk"
  args:
    executable: /bin/bash
  tags:
    - asterisk
    - system
- name: Change permissions of Asterisk-related files and directories
  remote_user: root
  shell: "chmod -R 750 /var/{lib,log,run,spool}/asterisk /usr/lib/asterisk /etc/asterisk"
  args:
    executable: /bin/bash
  tags:
    - asterisk
    - system
- name: Configure Asterisk UDP Transport
  remote_user: root
  blockinfile:
    path: /etc/asterisk/pjsip.conf
    block: |
      [0.0.0.0-udp]
      type=transport
      protocol=udp
      bind=0.0.0.0:5060
      external_media_address={{ asterisk_external_ip }}
      external_signaling_address={{ asterisk_external_ip }}
      allow_reload=no
      tos=cs3
      cos=3
      local_net={{ asterisk_localnet }}
  with_items:
    "{{ ip_addresses }}"
  tags:
    - system