- name: Add Asterisk logfile for Fail2Ban
  remote_user: root
  lineinfile:
    path: /etc/asterisk/logger.conf
    line: 'fail2ban => notice'
  tags:
    - asterisk
    - fail2ban
- name: Update Fail2Ban config
  remote_user: root
  template: src={{ item }}.j2 dest=/{{ item }}
  with_items:
    - etc/fail2ban/jail.local
  tags:
    - asterisk
    - fail2ban
- name: Restart Asterisk service
  remote_user: root
  systemd:
    state: restarted
    name: asterisk
- name: Restart Fail2ban service
  remote_user: root
  systemd:
    state: restarted
    name: fail2ban