- name: Download Asterisk source code
  remote_user: root
  ansible.builtin.get_url:
    url: "http://downloads.asterisk.org/pub/telephony/asterisk/asterisk-{{ asterisk_version }}.tar.gz"
    dest: "/usr/local/src"
  tags:
    - asterisk
- name: Unarchive Asterisk source code
  remote_user: root
  ansible.builtin.unarchive:
    copy: false
    src: "/usr/local/src/asterisk-{{ asterisk_version }}.tar.gz"
    dest: /usr/local/src
  tags:
  - asterisk
- name: Get Asterisk MP3 sources
  remote_user: root
  shell: ./contrib/scripts/get_mp3_source.sh
  args:
    chdir: "/usr/local/src/asterisk-{{ asterisk_version }}"
    executable: /bin/bash
  tags:
    - asterisk
- name: Install Asterisk dependencies
  remote_user: root
  shell: export DEBIAN_FRONTEND=noninteractive && ./contrib/scripts/install_prereq install
  args:
    chdir: "/usr/local/src/asterisk-{{ asterisk_version }}"
    executable: /bin/bash
  tags:
    - asterisk
    - system